kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.27.1
networking:
  disableDefaultCNI: true
  podSubnet: "10.201.0.0/16"
  serviceSubnet: "10.101.0.0/16"
