# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a reference.
version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - err113
    - errorlint
    - gocheckcompilerdirectives
    - goheader
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - musttag
    - reassign
    - revive
    - staticcheck
    - unused
  settings:
    goheader:
      values:
        regexp:
          PROJECT: Cilium|Hubble
      template: |-
        SPDX-License-Identifier: Apache-2.0
        Copyright Authors of {{ PROJECT }}
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cilium/cilium-cli
