# This policy allows packets towards {{.ExternalIP}}, but not {{.ExternalOtherIP}}.
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: client-egress-to-cidr
spec:
  endpointSelector:
    matchLabels:
      kind: client
  egress:
  - toCIDRSet:
    - cidr: {{.ExternalCIDR}}
      except:
      - {{.ExternalOtherIP}}/{{if isIPv6 .ExternalOtherIP}}128{{else}}32{{end}}
