apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-except-world
spec:
  endpointSelector: {}
  egress:
  - toEntities:
    - host
    - remote-node
    - cluster
    - init
    - health
    - kube-apiserver
  - toEndpoints:
      - {}
  {{- if .DNSCIDR }}
  - toPorts:
      - ports:
          - port: "53"
            protocol: ANY
    toCIDR:
      - "{{.DNSCIDR}}"
  {{- end }}
  ingress:
  - fromEntities:
    - host
    - remote-node
    - cluster
    - init
    - health
    - kube-apiserver
  - fromEndpoints:
    - {}
